[package]
name = "dele"
version = "0.1.0"
authors = ["koichiro <koichiro.okamoto.0805@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.0.0-pre.2"
globset = "0.3"
dirs = "3.0"
